apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: sum
  name: sum
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sum
    spec:
      containers:
      - image: nishedcob/operations-sum:20190116185402
        name: sum
        resources: {}
      restartPolicy: Always
status: {}
